# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [3]:
import numpy as np
arr=np.array([[1,2,3],
[4,2,5]])
print("Array is of type:",type(arr))
print(("No of dimensoins: ",arr.ndim))
print("Shape of array: ",arr.shape)
print("Size of array: ",arr.size)
print("Array stores elements of type: ",arr.dtype)


Array is of type: <class 'numpy.ndarray'>
('No of dimensoins: ', 2)
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int32


#### Create an array of 10 zeros 

In [6]:
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:",array)

An array of 10 zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### Create an array of 10 ones

In [7]:
import numpy as np
array=np.ones(10)
print("An array of 10 zeros:",array)

An array of 10 zeros: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#### Create an array of 10 fives

In [10]:
import numpy as np
array=np.ones(10)*5
print("An array of 10 fives:",array)


An array of 10 fives: [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


#### Create an array of the integers from 10 to 50

In [1]:
import numpy as np
array=np.arange(10,51)
print("Array of the integers from 10 to 50:",array)

Array of the integers from 10 to 50: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


#### Create an array of all the even integers from 10 to 50

In [2]:
import numpy as np
array=np.arange(10,51,2)
print("Array of even integers from 10 to 50:",array)

Array of even integers from 10 to 50: [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


#### Create a 3x3 matrix with values ranging from 0 to 8

In [14]:
import numpy as np
print(np.arange(0,9).reshape(3,3))


[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Create a 3x3 identity matrix

In [4]:
import numpy as np
array=np.identity(3)
print('3*3 matrix:')
print(array)

3*3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Use NumPy to generate a random number between 0 and 1

In [1]:
import numpy as np
rand_num=np.random.normal(0,1,1)
print("Random number between 0 and 1:",rand_num)

Random number between 0 and 1: [-0.45688014]


#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [2]:
import numpy as np
rand_num=np.random.normal(0,1,25)
print("25 random numbers from a standard normal distribution:",rand_num)


25 random numbers from a standard normal distribution: [-0.10586875  0.33458862  0.26883863  1.59051332  0.67035228  0.53634692
  0.30472061  3.01040702 -0.92558575  1.0793346   0.3714688   0.58288828
  1.89035579 -0.06560136  1.02945117  0.24420488 -0.93223251 -0.76098308
  0.34950226  0.05153771  0.52870021  0.65235654  0.35810687  1.87598428
 -0.06314765]


#### Create the following matrix:

In [5]:
array=np.arange(0.01,1.01,0.01).reshape(10,10)
print(array)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


#### Create an array of 20 linearly spaced points between 0 and 1:

In [6]:
import numpy as np
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [13]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [11]:
mat = np.arange(1,26).reshape(5,5)
mat
print(mat[3][-1])


20


In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

#### Get the standard deviation of the values in mat

In [15]:
mat = np.arange(1,26).reshape(5,5)
mat
print(mat.std())

7.211102550927978
